services:
  - type: web
    name: mlops-energy-api
    runtime: python
    env: python
    buildCommand: pip install --upgrade pip && pip install --only-binary :all: -r requirements_api.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
